#!/bin/bash
#
#	/etc/rc.d/init.d/graphite
#
# Starts the graphite carbon-cache daemon
#
# chkconfig: ?
# description: Frontend aggregatation of messages destined for graphite daemon
# processname: carbon-cache.py

# Source function library.
. /etc/rc.d/init.d/functions

[ -f /opt/graphite/bin/carbon-cache.py ] || exit 0

RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/graphite ]; then
	    echo -n $"Starting carbon-cache daemon: "
        /opt/graphite/bin/carbon-cache.py start
	    RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            touch /var/lock/subsys/graphite
            echo_success
        else
            echo_failure
        fi
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping carbon-cache daemon: "
    /opt/graphite/bin/carbon-cache.py stop
	RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        rm -f /var/lock/subsys/graphite
        echo_success
    else
        echo_failure
    fi
	echo
    return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	trap "" SIGHUP
	killall -HUP carbon-cache
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/graphite ]; then
	    restart
	fi
	;;
status)
	if [ -f /var/lock/subsys/graphite ]; then
        echo "carbon-cache is running"
        exit 0
    else
        echo "carbon-cache is stopped"
        exit 3
    fi
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	exit 1
esac

exit $RETVAL
