#!/bin/bash
#
#	/etc/rc.d/init.d/statsd
#
# Starts the statsd daemon
#
# chkconfig: ?
# description: Frontend aggregatation of messages destined for graphite daemon
# processname: statsd

# Source function library.
. /etc/rc.d/init.d/functions

[ -x /usr/local/bin/node ] || exit 0
[ -f /opt/statsd/stats.js ] || exit 0

RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/statsd ]; then
	    echo -n $"Starting statsd daemon: "
        # daemon
        /usr/local/bin/node /opt/statsd/stats.js /opt/statsd/exampleConfig.js 2>&1 >/dev/null &
	    RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            touch /var/lock/subsys/statsd
            echo_success
        else
            echo_failure
        fi
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping statsd daemon: "
    pid=$(ps wa | grep stats.js | grep node | awk '{print $1}')
    kill $pid
	RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        rm -f /var/lock/subsys/statsd
        echo_success
    else
        echo_failure
    fi
	echo
    return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	trap "" SIGHUP
	killall -HUP stats.js
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/statsd ]; then
	    restart
	fi
	;;
status)
	if [ -f /var/lock/subsys/statsd ]; then
        echo "statsd is running"
        exit 0
    else
        echo "statsd is stopped"
        exit 3
    fi
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
	exit 1
esac

exit $RETVAL
